image: egon0/docker-with-buildx-and-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    D_IMAGE_TAG: egon0/gitea-multiarch:$CI_COMMIT_REF_SLUG
    D_LATEST_TAG: egon0/gitea-multiarch:latest
  script:
    - apk add --no-cache jq wget
    - GITEA_VERSION=$(wget --quiet "https://api.github.com/repos/go-gitea/gitea/releases/latest" -O - |  jq -r '.tag_name') && wget https://github.com/go-gitea/gitea/archive/${GITEA_VERSION}.tar.gz -O /tmp/gitea.tar.gz
    - tar xf /tmp/gitea.tar.gz --strip-components=1
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker buildx create --use --name A$CI_COMMIT_SHORT_SHA
    - docker buildx build --platform $BUILD_PLATFORMS --push -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest -t $D_IMAGE_TAG -t $D_LATEST_TAG .
