image: egon0/docker-with-buildx-and-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

build:
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    D_IMAGE_TAG: egon0/gitea-multiarch:$CI_COMMIT_REF_SLUG
    D_LATEST_TAG: egon0/gitea-multiarch:latest
  script:
    - git clone https://github.com/go-gitea/gitea.git -b release/v1.14
    - cd gitea
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - docker buildx create --use --name A$CI_COMMIT_SHORT_SHA
    - docker buildx build --platform $BUILD_PLATFORMS --push -t $IMAGE_TAG -t $CI_REGISTRY_IMAGE:latest -t $D_IMAGE_TAG -t $D_LATEST_TAG .
